Disable packagekit in openqa_worker
os-autoinst/os-autoinst-distri-openQA pull request #109
Opened 2023-02-23 13:50 UTC by mimi1vx

use common function for all tests disabling packagekit

poo: https://progress.opensuse.org/issues/123496

2023-02-23 14:12 UTC, baierjan requested changes

2023-02-23 14:12 UTC, baierjan commented on lib/utils.pm
> +sub disable_packagkit {
```suggestion
sub disable_packagekit {
```

2023-02-23 14:12 UTC, baierjan commented on lib/utils.pm
> +our @EXPORT = qw(clear_root_console switch_to_x11 wait_for_desktop ensure_unlocked_desktop wait_for_container_log prepare_firefox_autoconfig disable_packagkit);
```suggestion
our @EXPORT = qw(clear_root_console switch_to_x11 wait_for_desktop ensure_unlocked_desktop wait_for_container_log prepare_firefox_autoconfig disable_packagekit);
```

2023-02-23 14:12 UTC, baierjan commented on tests/install/openqa_worker.pm
> +    disable_packagkit;
```suggestion
    disable_packagekit;
```

2023-02-23 15:48 UTC, Martchus commented
It would be great if the commit message would convey the bigger picture, e.g. "Avoid GNOME auth dialog by disabling packagekit".

2023-02-23 18:01 UTC, mimi1vx commented
> It would be great if the commit message would convey the bigger picture, e.g. "Avoid GNOME auth dialog by disabling packagekit".

there is question if auth dialog was caused by packagekit ... must look into TW Gnome what else acts as update service and can ask for rights

2023-02-24 10:14 UTC, baierjan approved these changes
Seems ok

2023-02-24 12:01 UTC, kalikiana approved these changes

2023-02-24 12:01 UTC, merged