Remove ack installation and usage from test_running
os-autoinst/os-autoinst-distri-openQA pull request #128
Opened 2023-06-21 09:50 UTC by mimi1vx

2023-06-21 10:21 UTC, Martchus commented
I suppose it makes sense to avoid calling zypper just for ack. Is this related to a ticket?

2023-06-21 10:57 UTC, okurz requested changes
Please provide proper reasoning in pull requests otherwise we don't know why you do that and what you intend with it. I suggest also to reference the commit that brought in the change originally showing that you understood why something was done in the past and then describe what changed to improve by not doing that anymore

2023-06-21 16:05 UTC, perlpunk commented
> ack was here used only as a more advanced grep which isn't necessary. grep has the same functionality and is installed by default.

I think `grep` doesn't provide the same `--passthru` functionality as `ack` - always print complete output even if it doesn't match. See e8439ddf8c4e35947d151726fa83cf8e4ef421df

But #128 fixes the actual problem, so I think this is obsolete.

2023-06-22 08:53 UTC, mimi1vx commented
> > ack was here used only as a more advanced grep which isn't necessary. grep has the same functionality and is installed by default.
> 
> I think `grep` doesn't provide the same `--passthru` functionality as `ack` - always print complete output even if it doesn't match. See [e8439dd](https://github.com/os-autoinst/os-autoinst-distri-openQA/commit/e8439ddf8c4e35947d151726fa83cf8e4ef421df)
> 

which isn't important because if isn't match -> tests fail and postfail calls `openqa-cli api jobs` plus `journal` etc ...

2023-06-22 09:11 UTC, okurz commented
I'd still prefer to keep ack as is

2023-07-18 18:08 UTC, kalikiana commented
> But #128 fixes the actual problem, so I think this is obsolete.

You seem to be referencing this very same PR. What did you mean to refer to?

I can see how avoiding a zypper call makes the test more reliable. So I would be inclined to second the change... but we should simply agree on what we prefer and how hard we want to work around infra and tooling outside our control.

2023-07-19 01:42 UTC, perlpunk commented
> > But #128 fixes the actual problem, so I think this is obsolete.
> 
> @perlpunk You seem to be referencing this very same PR. What did you mean to refer to?

sorry, I meant #129 :)

2023-07-20 16:21 UTC, kalikiana commented
> > > But #128 fixes the actual problem, so I think this is obsolete.
> > 
> > 
> > @perlpunk You seem to be referencing this very same PR. What did you mean to refer to?
> 
> sorry, I meant #129 :)

Ah, right. This also has the context I was looking for.

@mimi1vx So I would close this one for now. If installing ack is leading to recurring failures I'd say we best have a separate ticket and discuss it as part of the estimation.

2023-07-20 16:21 UTC, closed without merging