Add search test written in Python
os-autoinst/os-autoinst-distri-openQA pull request #68
Opened 2021-04-23 06:42 UTC by kalikiana

See: https://progress.opensuse.org/issues/91257

2021-04-23 07:44 UTC, grisu48 reviewed
This looks already very promising!

2021-04-23 10:09 UTC, okurz commented
actually good idea :)

2021-05-14 16:20 UTC, okurz commented on tests/openQA/search.py
> +    script_run('openqa-cli api --o3 experimental/search q=shutdown.pm')
as you run within the openQA-in-openQA instance that setup an openQA instance I recommend to connect to that, not "o3". As "localhost" is default I suggest to simply delete the parameter and then have a test that works with that instance.

2021-05-14 16:20 UTC, okurz commented on tests/openQA/search.py
> +    save_screenshot()
Isn't there a screenshot already after the script_run call finished?

2021-07-14 14:29 UTC, Martchus commented on tests/openQA/search.py
> +    return dict([('fatal', 1)])
```suggestion
    return {'fatal': 1}
```

2021-07-14 17:13 UTC, okurz requested changes

2021-07-14 17:13 UTC, okurz commented on main.pm
> +    # use Inline Python => "import os.path, sys; sys.path.insert(0, os.path.abspath(os.path.join(os.path.curdir, '../..')))";
delete dead code

2021-07-14 17:13 UTC, okurz commented on tests/openQA/search.py
> +
Why do you want to introduce a GPL licensed file? Other files within the repo don't have that license header and the project is MIT-licensed. I suggest to simply delete the header

2021-07-14 17:13 UTC, okurz commented on tests/openQA/search.py
> +    send_key('ctrl-alt-f3')  # switch to root console
```suggestion

def switch_to_root_console():
    send_key('ctrl-alt-f3')

def post_fail_hook(self):
```

2021-07-14 17:13 UTC, okurz commented on tests/openQA/search.py
> +    script_run('openqa-cli api experimental/search q=shutdown.pm')
Please use `assert_script_run` unless you want to check the exit code explicitly

2021-07-14 17:29 UTC, okurz approved these changes
This looks great now and could act as a very good example!

Care to mention it in the openQA documentation as showcase example? :)

2021-07-14 17:29 UTC, merged