Make use of launcher wheel
os-autoinst/os-autoinst-distri-openQA pull request #82
Opened 2022-03-28 17:31 UTC by kalikiana

Fixes: https://progress.opensuse.org/issues/108530

2022-03-28 18:10 UTC, okurz commented
You might be able to test it (maybe only on o3-openqaworker7) by forking
https://build.opensuse.org/package/show/devel:openQA/isotovideo-qemu-kvm
and building your own container from https://github.com/kalikiana/os-autoinst/tree/git_wheel_support and then

```
openqa-clone-job --within-instance https://openqa.opensuse.org/t... WORKER_CLASS=openqaworker7 \
ISOTOVIDEO="podman run --rm -it registry.opensuse.org/home/kalikiana/branches/devel/openqa/containers/isotovideo:qemu-kvm /usr/bin/isotovideo -d" \
CASEDIR=https://github.com/kalikiana/os-autoinst-distri-openQA/tree/wheel_launcher
```

2022-08-03 14:15 UTC, okurz approved these changes

2022-08-03 14:16 UTC, okurz commented
https://openqa.opensuse.org/tests/2494128

2022-08-03 14:18 UTC, okurz commented on wheels.yaml
> +wheels:
```suggestion
version: v0.1
wheels:
```

2022-08-03 14:49 UTC, okurz commented
o3 workers were outdated, see https://progress.opensuse.org/issues/114941 . Now retriggered as https://openqa.opensuse.org/tests/2494138

2022-08-03 17:32 UTC, okurz requested changes
https://openqa.opensuse.org/tests/2494766#step/dashboard/5 fails with

```
# Test died: Odd name/value argument for subroutine 'OpenQA::Wheel::Launcher::start_gui_program' at /var/lib/openqa/pool/14/os-autoinst-distri-openQA//tests/openQA/dashboard.pm line 11.
```

2022-08-03 18:13 UTC, kalikiana commented on wheels.yaml
> +wheels:
I don't see a difference

2022-08-03 18:23 UTC, okurz commented
Retriggered test https://openqa.opensuse.org/tests/2494826

2022-08-03 18:34 UTC, okurz approved these changes
https://openqa.opensuse.org/tests/2494826#step/dashboard/7 is good

2022-08-03 18:35 UTC, okurz commented on wheels.yaml
> +wheels:
Because you meanwhile added it

2022-08-03 18:35 UTC, merged